import { initDb } from "../db/client.js";
import { computeFullReport } from "./MetricsCalculator.js";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function formatPct(val: number | null): string {
  return val !== null ? `${val.toFixed(1)}%` : "N/A";
}

function formatNum(val: number | null, decimals = 1): string {
  return val !== null ? val.toFixed(decimals) : "N/A";
}

function formatDuration(seconds: number | null): string {
  if (seconds === null) return "N/A";
  if (seconds < 60) return `${seconds.toFixed(0)}s`;
  return `${(seconds / 60).toFixed(1)}m`;
}

async function main() {
  await initDb();

  // Default: report for the last 7 days
  const daysArg = parseInt(process.argv[2] || "7");
  const since = new Date(Date.now() - daysArg * 24 * 60 * 60 * 1000);

  console.log(`Generating metrics report for the last ${daysArg} days (since ${since.toISOString()})...`);

  const report = await computeFullReport(since);

  const { layer2, layer3, layer4 } = report;

  const markdown = `# NarrativeDesk Weekly Metrics Report

Generated: ${report.generatedAt}
Period: ${layer2.periodStart || "N/A"} to ${layer2.periodEnd || "N/A"}

---

## Layer 2: Decision Metrics

### Classification Breakdown
| Classification | Count | Percentage |
|---------------|-------|------------|
| Ignore | ${layer2.classificationBreakdown.ignore} | ${formatPct(layer2.classificationBreakdown.total > 0 ? (layer2.classificationBreakdown.ignore / layer2.classificationBreakdown.total) * 100 : null)} |
| Monitor | ${layer2.classificationBreakdown.monitor} | ${formatPct(layer2.classificationBreakdown.total > 0 ? (layer2.classificationBreakdown.monitor / layer2.classificationBreakdown.total) * 100 : null)} |
| Act | ${layer2.classificationBreakdown.act} | ${formatPct(layer2.classificationBreakdown.total > 0 ? (layer2.classificationBreakdown.act / layer2.classificationBreakdown.total) * 100 : null)} |
| **Total** | **${layer2.classificationBreakdown.total}** | |

### Thesis Updates
- Total thesis updates: ${layer2.thesisDeltaSummary.totalUpdates}
- No-change decisions: ${layer2.thesisDeltaSummary.noChangeCount}
- Thesis update rate: ${formatPct(layer2.thesisDeltaSummary.updateRate)}

### Sub-Agent Credibility Correlation
| Classification | Avg Credibility Rating |
|---------------|----------------------|
| Act | ${formatNum(layer2.subAgentCorrelation.avgRatingForAct)} |
| Monitor | ${formatNum(layer2.subAgentCorrelation.avgRatingForMonitor)} |
| Ignore | ${formatNum(layer2.subAgentCorrelation.avgRatingForIgnore)} |

High-credibility (>=4) act rate: ${formatPct(layer2.subAgentCorrelation.highCredibilityActRate)}

---

## Layer 3: Trade Outcome Metrics

| Metric | Value |
|--------|-------|
| Total trades | ${layer3.totalTrades} |
| Closed trades | ${layer3.closedTrades} |
| Open trades | ${layer3.openTrades} |
| Win rate | ${formatPct(layer3.winRate)} |
| Avg win | ${formatPct(layer3.avgWinPct)} |
| Avg loss | ${formatPct(layer3.avgLossPct)} |
| Profit factor | ${formatNum(layer3.profitFactor)} |
| Invalidation accuracy | ${formatPct(layer3.invalidationAccuracy)} |
| Avg hold duration | ${layer3.avgHoldDurationMinutes !== null ? `${layer3.avgHoldDurationMinutes.toFixed(0)} min` : "N/A"} |

---

## Layer 4: HITL Metrics

### Approval Breakdown
| Status | Count | Rate |
|--------|-------|------|
| Approved | ${layer4.approvedCount} | ${formatPct(layer4.approvalRate)} |
| Rejected | ${layer4.rejectedCount} | ${formatPct(layer4.rejectionRate)} |
| Edited | ${layer4.editedCount} | ${formatPct(layer4.editRate)} |
| Expired | ${layer4.expiredCount} | ${formatPct(layer4.expirationRate)} |
| **Total** | **${layer4.totalApprovals}** | |

### Decision Timing
- Avg time to decision: ${formatDuration(layer4.avgTimeToDecisionSeconds)}

### Tag Distribution
${Object.entries(layer4.tagBreakdown).length > 0
  ? Object.entries(layer4.tagBreakdown)
      .map(([tag, count]) => `- ${tag}: ${count}`)
      .join("\n")
  : "No tags recorded yet."}

### Rejection vs Hindsight (15m price change after rejected proposals)
${layer4.rejectionVsOutcome.length > 0
  ? layer4.rejectionVsOutcome
      .map((r) => `- ${r.tag} (n=${r.count}): avg 15m price change ${formatPct(r.avgPriceChange15m)}`)
      .join("\n")
  : "No rejection outcome data yet."}

---

*Report generated by NarrativeDesk MetricsCalculator*
`;

  // Write report to reports/ directory
  const reportDir = join(__dirname, "..", "..", "reports");
  if (!existsSync(reportDir)) {
    mkdirSync(reportDir, { recursive: true });
  }

  const dateStr = new Date().toISOString().split("T")[0];
  const reportPath = join(reportDir, `metrics-${dateStr}.md`);
  writeFileSync(reportPath, markdown, "utf-8");
  console.log(`Report written to: ${reportPath}`);

  process.exit(0);
}

main().catch((err) => {
  console.error("Report generation failed:", err);
  process.exit(1);
});
